name: Delete Beta Releases

on: 
  workflow_dispatch:
    
jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 10 
          delete_tags: true 
          delete_tag_pattern: _b
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
